name: ondevice_slm_app
description: A small Flutter starter app for OnDevice SLM Inference
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  path_provider: ^2.0.15
  flutter_llama: ^1.1.2
  file_picker: ^5.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/
